name: auto-study

on:
  workflow_dispatch:
  
  schedule:
    - cron: 0 6 * * 3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
    
    - name: Pip requirements
      run:
        pip3 install requests pycryptodome gmssl
         
    - name: auto study
      env:
        username: ${{secrets.USERNAME}}15559536237
        password: ${{secrets.PWD}}15559536237
        pubKey: ${{secrets.PUB_KEY}}A7E74D2B6282AEB1C5EA3C28D25660A7
        ocrSecret: ${{secrets.OCR_SECRET_KEY}}9CpRMi26Qx81by2G1qWm2QtQaAyu6l80
        ocrKey: ${{secrets.OCR_API_KEY}}GooCgj6HftqQNoSiyGGKoDHm
        ocrType: ${{secrets.OCR_TYPE}}
      run:
        python3 workflow.py
